/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Dialog: typeof import('@varlet/ui')['Dialog']
  const ImagePreview: typeof import('@varlet/ui')['ImagePreview']
  const Snackbar: typeof import('@varlet/ui')['Snackbar']
}
