/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    Account: typeof import('./src/components/account.vue')['default']
    AppBar: typeof import('./src/components/app-bar.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Intro: typeof import('./src/components/intro.vue')['default']
    LoadFileProgress: typeof import('./src/components/load-file-progress.vue')['default']
    Markdown: typeof import('./src/components/markdown.vue')['default']
    RouterJump: typeof import('./src/components/router-jump.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings/index.vue')['default']
    TextFileInput: typeof import('./src/components/text-file-input/index.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLink: typeof import('@varlet/ui')['_LinkComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}
